import { Server } from 'node:http';

import request from 'supertest';

import { SWAGGER_JSON_PATH, SWAGGER_PATH } from '../src/main';
import { TestApp, startTestApp } from './test-app.fixture';

/**
 * Read one directive out of a Content-Security-Policy header, e.g.
 * `script-src 'self'`. Returns undefined when the policy does not set it.
 */
const directive = (policy: string, name: string): string | undefined =>
  policy
    .split(';')
    .map((part) => part.trim())
    .find((part) => part === name || part.startsWith(`${name} `));

/** Every `<script ...>` opening tag in a document, in order. */
const scriptTags = (html: string): string[] =>
  html.match(/<script\b[^>]*>/g) ?? [];

/**
 * Endpoints that between them cover every kind of response the app serves: a
 * JSON collection, a health probe, the generated spec, and the only HTML page.
 */
const PATHS = ['/livestream', '/__heartbeat__', `/${SWAGGER_JSON_PATH}`];

describe('Security headers (e2e)', () => {
  let fixture: TestApp;
  let server: Server;

  beforeAll(async () => {
    fixture = await startTestApp();
    server = fixture.server;
  }, 30_000);

  afterAll(async () => {
    await fixture?.close();
  });

  describe.each([...PATHS, `/${SWAGGER_PATH}`])('%s', (path) => {
    it('is served with the security headers helmet applies', async () => {
      const res = await request(server).get(path);

      expect(res.status).toBe(200);
      expect(res.headers['content-security-policy']).toBeDefined();
      expect(res.headers['x-content-type-options']).toBe('nosniff');
      expect(res.headers['x-frame-options']).toBe('SAMEORIGIN');
      expect(res.headers['referrer-policy']).toBe('no-referrer');
      expect(res.headers['strict-transport-security']).toBeDefined();
    });

    it('does not advertise the framework it runs on', async () => {
      const res = await request(server).get(path);

      expect(res.headers['x-powered-by']).toBeUndefined();
    });
  });

  // A 404 is generated by Nest rather than a controller, so it exercises a
  // different path through the stack than the routes above.
  it('applies the headers to error responses too', async () => {
    const res = await request(server).get('/livestream/not-a-real-channel');

    expect(res.status).toBe(404);
    expect(res.headers['x-content-type-options']).toBe('nosniff');
    expect(res.headers['x-powered-by']).toBeUndefined();
  });

  describe('the default policy against what the Swagger UI needs', () => {
    let html: string;
    let policy: string;

    beforeAll(async () => {
      const res = await request(server).get(`/${SWAGGER_PATH}`);
      html = res.text;
      policy = res.headers['content-security-policy'];
    });

    it('locks scripts to this origin, and the UI loads none from anywhere else', () => {
      expect(directive(policy, 'script-src')).toBe("script-src 'self'");

      const tags = scriptTags(html);
      expect(tags.length).toBeGreaterThan(0);
      // Every script is external — an inline one would be blocked outright,
      // which is what would break the UI under this policy.
      expect(tags.filter((tag) => !/\ssrc=/.test(tag))).toEqual([]);
      // ...and relative, so it resolves to this origin and 'self' allows it.
      const sources = tags.map((tag) => /src=['"]?([^'">\s]+)/.exec(tag)?.[1]);
      expect(
        sources.filter((src) => !src || /^[a-z]+:|^\/\//.test(src)),
      ).toEqual([]);
    });

    it('forbids inline event handlers, and the UI uses none', () => {
      expect(directive(policy, 'script-src-attr')).toBe(
        "script-src-attr 'none'",
      );
      expect(/<[a-z][^>]*\son[a-z]+\s*=/i.test(html)).toBe(false);
    });

    it('allows the inline styles the UI ships with', () => {
      // The page carries inline <style> blocks and a style attribute, so the
      // policy has to permit them; dropping 'unsafe-inline' would break layout.
      expect(html).toMatch(/<style>/);
      expect(directive(policy, 'style-src')).toContain("'unsafe-inline'");
    });
  });
});
