import { Server } from 'node:http';

import { INestApplication } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';
import { Test } from '@nestjs/testing';
import request from 'supertest';

import { AppController } from '../src/app.controller';
import { HealthModule } from '../src/health';
import { getVersionInfo } from '../src/health/version';
import { LivestreamModule } from '../src/livestream';
import {
  SWAGGER_JSON_PATH,
  SWAGGER_PATH,
  setupSecurity,
  setupSwagger,
} from '../src/main';

/** The livestream service needs a channel list to boot; one is enough here. */
const CHANNELS = 'FixtureAlpha:fixture-alpha';

/**
 * Minimal stand-ins for the two upstreams the livestream service talks to on
 * startup: enough for discovery to complete without reaching the network.
 */
const fetchStub = (input: unknown): Response => {
  const url = new URL(String(input));
  if (url.hostname === 'www.googleapis.com') {
    return new Response(JSON.stringify({ items: [{ id: 'UCfixture' }] }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }
  return new Response(
    '<?xml version="1.0" encoding="UTF-8"?>' +
      '<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" ' +
      'xmlns="http://www.w3.org/2005/Atom"><title>Fixture Alpha</title></feed>',
    { status: 200, headers: { 'content-type': 'application/atom+xml' } },
  );
};

/**
 * Read one directive out of a Content-Security-Policy header, e.g.
 * `script-src 'self'`. Returns undefined when the policy does not set it.
 */
const directive = (policy: string, name: string): string | undefined =>
  policy
    .split(';')
    .map((part) => part.trim())
    .find((part) => part === name || part.startsWith(`${name} `));

/** Every `<script ...>` opening tag in a document, in order. */
const scriptTags = (html: string): string[] =>
  html.match(/<script\b[^>]*>/g) ?? [];

/**
 * Endpoints that between them cover every kind of response the app serves: a
 * JSON collection, a health probe, the generated spec, and the only HTML page.
 */
const PATHS = ['/livestream', '/__heartbeat__', `/${SWAGGER_JSON_PATH}`];

describe('Security headers (e2e)', () => {
  let app: INestApplication;
  let server: Server;
  const originalFetch = globalThis.fetch;

  beforeAll(async () => {
    // Stubbed before init() because the livestream service calls out on startup.
    globalThis.fetch = jest.fn((input: unknown) =>
      Promise.resolve(fetchStub(input)),
    );

    const moduleRef = await Test.createTestingModule({
      imports: [
        ConfigModule.forRoot({
          isGlobal: true,
          ignoreEnvFile: true,
          load: [
            () => ({
              YOUTUBE_API_KEY: 'test-key',
              LIVESTREAM_CHANNELS: CHANNELS,
            }),
          ],
        }),
        HealthModule.register({ version: getVersionInfo() }),
        LivestreamModule,
      ],
      controllers: [AppController],
    }).compile();

    app = moduleRef.createNestApplication({ logger: false });
    // Same order as bootstrap(): headers first, so they also cover the routes
    // Swagger mounts next.
    setupSecurity(app);
    setupSwagger(app);
    await app.init();
    server = app.getHttpServer();
  }, 30_000);

  afterAll(async () => {
    // Clears the discovery/reconcile intervals so Jest can exit cleanly.
    await app?.close();
    globalThis.fetch = originalFetch;
  });

  describe.each([...PATHS, `/${SWAGGER_PATH}`])('%s', (path) => {
    it('is served with the security headers helmet applies', async () => {
      const res = await request(server).get(path);

      expect(res.status).toBe(200);
      expect(res.headers['content-security-policy']).toBeDefined();
      expect(res.headers['x-content-type-options']).toBe('nosniff');
      expect(res.headers['x-frame-options']).toBe('SAMEORIGIN');
      expect(res.headers['referrer-policy']).toBe('no-referrer');
      expect(res.headers['strict-transport-security']).toBeDefined();
    });

    it('does not advertise the framework it runs on', async () => {
      const res = await request(server).get(path);

      expect(res.headers['x-powered-by']).toBeUndefined();
    });
  });

  // A 404 is generated by Nest rather than a controller, so it exercises a
  // different path through the stack than the routes above.
  it('applies the headers to error responses too', async () => {
    const res = await request(server).get('/livestream/not-a-real-channel');

    expect(res.status).toBe(404);
    expect(res.headers['x-content-type-options']).toBe('nosniff');
    expect(res.headers['x-powered-by']).toBeUndefined();
  });

  describe('the default policy against what the Swagger UI needs', () => {
    let html: string;
    let policy: string;

    beforeAll(async () => {
      const res = await request(server).get(`/${SWAGGER_PATH}`);
      html = res.text;
      policy = res.headers['content-security-policy'];
    });

    it('locks scripts to this origin, and the UI loads none from anywhere else', () => {
      expect(directive(policy, 'script-src')).toBe("script-src 'self'");

      const tags = scriptTags(html);
      expect(tags.length).toBeGreaterThan(0);
      // Every script is external — an inline one would be blocked outright,
      // which is what would break the UI under this policy.
      expect(tags.filter((tag) => !/\ssrc=/.test(tag))).toEqual([]);
      // ...and relative, so it resolves to this origin and 'self' allows it.
      const sources = tags.map((tag) => /src=['"]?([^'">\s]+)/.exec(tag)?.[1]);
      expect(
        sources.filter((src) => !src || /^[a-z]+:|^\/\//.test(src)),
      ).toEqual([]);
    });

    it('forbids inline event handlers, and the UI uses none', () => {
      expect(directive(policy, 'script-src-attr')).toBe(
        "script-src-attr 'none'",
      );
      expect(/<[a-z][^>]*\son[a-z]+\s*=/i.test(html)).toBe(false);
    });

    it('allows the inline styles the UI ships with', () => {
      // The page carries inline <style> blocks and a style attribute, so the
      // policy has to permit them; dropping 'unsafe-inline' would break layout.
      expect(html).toMatch(/<style>/);
      expect(directive(policy, 'style-src')).toContain("'unsafe-inline'");
    });
  });
});
